package main

import (
	"fmt"
	"log"
)

// StartMessageProcessors subscribes to the message bus and processes incoming messages.
func StartMessageProcessors() {
	log.Printf("Starting message processors...")

	// Goroutine for handling status changes (Fan-Out Processor)
	go func() {
		statusCh := messageBus.SubscribeStatus()
		for msg := range statusCh {
			log.Printf("🔔 STATUS CHANGE: Entity %s changed from %s to %s", msg.EntityName, msg.OldStatus, msg.NewStatus)

			// 1. Get all registered devices.
			// In a future state, this would get devices subscribed to this specific entity.
			devices, err := db.GetAllDevices()
			if err != nil {
				log.Printf("Error getting devices for fan-out: %v", err)
				continue
			}

			// if len(devices) == 0 {
			// 	log.Printf("FAN-OUT: No devices found for entity %s", msg.EntityID)
			// 	continue
			// }

			// log.Printf("FAN-OUT: Found %d devices. Enqueuing APNs jobs...", len(devices))

			// 2. Create and enqueue a push notification for each device.
			notificationMsg := fmt.Sprintf("%s: %s -> %s", msg.EntityName, msg.OldStatus, msg.NewStatus)
			for _, device := range devices {
				pushReq := PushRequest{
					DeviceToken:    device.DeviceToken,
					Message:        notificationMsg,
					EntityID:       msg.EntityID,
					EntityName:     msg.EntityName,
					ParkID:         msg.ParkID,
					OldStatus:      string(msg.OldStatus),
					NewStatus:      string(msg.NewStatus),
					OldWaitTime:    msg.OldWaitTime,
					NewWaitTime:    msg.NewWaitTime,
					Environment:    device.Environment,
					NotificationID: "", // Will be auto-generated by the worker
					Timestamp:      msg.Timestamp, // UTC timestamp when websocket message was received
				}
				// Use the non-blocking Push function
				Push(pushReq)
			}
		}
	}()

	// Goroutine for handling wait time changes
	// TODO: Re-enable when working on wait time functionality
	// go func() {
	// 	waitTimeCh := messageBus.SubscribeWaitTime()
	// 	for msg := range waitTimeCh {
	// 		log.Printf("⏰ WAIT TIME CHANGE: Entity %s changed from %d to %d minutes at %v",
	// 			msg.EntityID, msg.OldWaitTime, msg.NewWaitTime, msg.Timestamp)
	// 	}
	// }()
} 